version: '3.9'
services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --set
      - redpanda.cluster_id=turning-red
      - --set
      - redpanda.enable_idempotence=true
      - --set
      - redpanda.enable_transactions=true
      - --set
      - redpanda.auto_create_topics_enabled=true
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://0.0.0.0:9092
    image: docker.vectorized.io/vectorized/redpanda:v22.3.11-arm64
    container_name: redpanda
    ports:
      - 9092:9092
      - 29092:29092
  console:
    image: docker.redpanda.com/vectorized/console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - "8082:8080"
    depends_on:
      - redpanda
  crdb:
    image: cockroachdb/cockroach
    ports:
      - "26257:26257"
      - "8081:8080"
    command: start-single-node --insecure
